# Generated by Django 2.1.7 on 2019-03-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videoteca', '0003_auto_20190320_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Bboy')),
                ('nacionalidad', models.CharField(blank=True, max_length=80, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Powermove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='PowerMove')),
                ('resumen', models.TextField(blank=True, verbose_name='Resumen')),
                ('bboys', models.ManyToManyField(to='videoteca.Bboy')),
            ],
        ),
    ]
