# Generated by Django 2.1.7 on 2019-03-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0004_bboy_powermove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powermove',
            name='bboys',
        ),
    ]
