# Generated by Django 2.1.7 on 2019-03-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0005_remove_powermove_bboys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Powermove',
        ),
        migrations.RenameField(
            model_name='bboy',
            old_name='nombre',
            new_name='name',
        ),
    ]
