# Generated by Django 2.1.7 on 2019-03-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0007_powermove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powermove',
            name='bboy',
        ),
        migrations.AddField(
            model_name='powermove',
            name='bboy',
            field=models.ManyToManyField(to='videoteca.Bboy'),
        ),
    ]
