# Generated by Django 2.1.7 on 2019-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoteca', '0009_auto_20190325_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bboy',
            name='powermove',
        ),
        migrations.AddField(
            model_name='powermove',
            name='bboy',
            field=models.ManyToManyField(to='videoteca.Bboy'),
        ),
    ]
